############## turtle light oneline factorized
root                           ::= triples+ 
triples                           ::= WS? triple WS? "." 
triple                           ::= subj WS? predicateObjectList
predicateObjectList                           ::= pred objectList ( WS?  ";"  WS? ( pred   WS? objectList)? )*
objectList                        ::= obj  (  WS? ","  WS? obj  )* 
subj                           ::=  iri
pred                           ::= iri | "a"
obj                           ::= iri | string
string                           ::= WS? "\"" [ \t!#-\[\]-~]* "\"" WS?
iri                           ::= ":" PN_LOCAL+  
WS                       ::= [ \t\n]
PN_CHARS_BASE                  ::= [A-Z] | [a-z] | [#x00C0-#x00D6] | [#x00D8-#x00F6] | [#x00F8-#x02FF] | [#x0370-#x037D] | [#x037F-#x1FFF] | [#x200C-#x200D] | [#x2070-#x218F] | [#x2C00-#x2FEF] | [#x3001-#xD7FF] | [#xF900-#xFDCF] | [#xFDF0-#xFFFD] | [#x10000-#xEFFFF] 
PN_CHARS_U                     ::= PN_CHARS_BASE | "_" 
PN_LOCAL                       ::= ( PN_CHARS_U | ":" | [0-9] | PLX ) ( ( PN_CHARS | "." | ":" | PLX )*  ( PN_CHARS | ":" | PLX ) ) ?
PLX                            ::= PERCENT | PN_LOCAL_ESC
PN_CHARS                       ::= PN_CHARS_U | "-" | [0-9] | [#x00B7] | [#x0300-#x036F] | [#x203F-#x2040] 
PERCENT                        ::= "%" HEX HEX
HEX                            ::= [0-9] | [A-F] | [a-f]
PN_LOCAL_ESC                   ::= "\\" ( "_" | "~" | "." | "-" | "!" | "$" | "&" | "'" | "(" | ")" | "*" | "+" | "," | ";" | "=" | "/" | "?" | "#" | "@" | "%" )